# Project Settings
BASENAME     := tsumitobatsu
BUILD_DIR    := build
ASM_DIR      := asm
LD_SCRIPT    := $(BASENAME).ld
TARGET_ELF   := $(BUILD_DIR)/$(BASENAME).elf

# Tools
CROSS_COMPILE := mips-linux-gnu-
AS            := $(CROSS_COMPILE)as
LD            := $(CROSS_COMPILE)ld
OBJCOPY       := $(CROSS_COMPILE)objcopy

# Flags
ASFLAGS      := -march=vr4300 -mabi=32 -I include
LDFLAGS      := -T $(LD_SCRIPT) -Map $(BUILD_DIR)/$(BASENAME).map \
                --unresolved-symbols=ignore-all \
                --no-check-sections \
                --noinhibit-exec

# Find all assembly files generated by splat
ASM_FILES    := $(shell find $(ASM_DIR) -name "*.s")
OBJ_FILES    := $(patsubst $(ASM_DIR)/%.s,$(BUILD_DIR)/$(ASM_DIR)/%.o,$(ASM_FILES))

# Find all bin files in the assets folder
ASSET_DIR    := assets
BIN_FILES    := $(shell find $(ASSET_DIR) -name "*.bin")
# Treat bins as objects for the linker
BIN_OBJ_FILES := $(patsubst $(ASSET_DIR)/%.bin,$(BUILD_DIR)/$(ASSET_DIR)/%.o,$(BIN_FILES))

# Update the all target to include BIN_OBJ_FILES
all: $(TARGET_ELF)

# Link the ELF file including the new bin objects
$(TARGET_ELF): $(OBJ_FILES) $(BIN_OBJ_FILES)
	@mkdir -p $(@D)
	$(LD) $(LDFLAGS) -o $@

# Rule for .s files
$(BUILD_DIR)/$(ASM_DIR)/%.o: $(ASM_DIR)/%.s
	@mkdir -p $(@D)
	$(AS) $(ASFLAGS) $< -o $@

# Rule for converting .bin files into linkable .o files
$(BUILD_DIR)/$(ASSET_DIR)/%.o: $(ASSET_DIR)/%.bin
	@mkdir -p $(@D)
	$(OBJCOPY) -I binary -O elf32-bigmips -B mips $< $@

$(BUILD_DIR)/$(ASSET_DIR)/%.o: $(ASSET_DIR)/%.bin
	@mkdir -p $(@D)
	echo '.section .data; .incbin "$<"' | $(AS) $(ASFLAGS) -o $@ -

clean:
	rm -rf $(BUILD_DIR)

.PHONY: all clean